In [1]:
!pip install ta
import ta
import sqlalchemy
import pandas as pd
import yfinance as yf
import numpy as np

Requirement already satisfied: ta in c:\users\user\anaconda3\lib\site-packages (0.10.2)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from ta) (1.16.5)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (from ta) (0.25.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\user\anaconda3\lib\site-packages (from pandas->ta) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\user\anaconda3\lib\site-packages (from pandas->ta) (2.8.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas->ta) (1.12.0)

In [2]:
url='https://raw.githubusercontent.com/charlesy1018/HKSTOCK-market-daily-check/main/HangSeng_Index_StockList.csv'
HSI_stock_ticker=pd.read_csv(url)
print(HSI_stock_ticker)

     Symbol            Name
0   0001.HK    CKH HOLDINGS
1   0002.HK    CLP HOLDINGS
2   0003.HK  HK & CHINA GAS
3   0005.HK   HSBC HOLDINGS
4   0006.HK    POWER ASSETS
..      ...             ...
70  6862.HK        HAIDILAO
71  9618.HK           JD-SW
72  9633.HK   NONGFU SPRING
73  9988.HK         BABA-SW
74  9999.HK          NTES-S

[75 rows x 2 columns]

In [3]:
HSI_symbol = HSI_stock_ticker.Symbol.to_list()
print(HSI_symbol)

['0001.HK', '0002.HK', '0003.HK', '0005.HK', '0006.HK', '0011.HK', '0012.HK', '0016.HK', '0017.HK', '0027.HK', '0066.HK', '0101.HK', '0175.HK', '0241.HK', '0267.HK', '0288.HK', '0291.HK', '0316.HK', '0322.HK', '0386.HK', '0388.HK', '0669.HK', '0688.HK', '0700.HK', '0762.HK', '0823.HK', '0857.HK', '0868.HK', '0881.HK', '0883.HK', '0939.HK', '0941.HK', '0960.HK', '0968.HK', '0981.HK', '0992.HK', '1038.HK', '1044.HK', '1088.HK', '1093.HK', '1109.HK', '1113.HK', '1177.HK', '1209.HK', '1211.HK', '1299.HK', '1378.HK', '1398.HK', '1810.HK', '1876.HK', '1928.HK', '1929.HK', '1997.HK', '2007.HK', '2020.HK', '2269.HK', '2313.HK', '2318.HK', '2319.HK', '2331.HK', '2382.HK', '2388.HK', '2628.HK', '2688.HK', '3690.HK', '3692.HK', '3968.HK', '3988.HK', '6098.HK', '6690.HK', '6862.HK', '9618.HK', '9633.HK', '9988.HK', '9999.HK']

In [4]:
url2= "https://raw.githubusercontent.com/charlesy1018/HKSTOCK-market-daily-check/main/Hang%20Seng%20MidCap-StockList.csv"
midcap_stock_ticker=pd.read_csv(url2)
print(midcap_stock_ticker)

      Symbol             Name
0    0008.HK             PCCW
1    0013.HK         HUTCHMED
2    0014.HK        HYSAN DEV
3    0019.HK  SWIRE PACIFIC A
4    0023.HK   BANK OF E ASIA
..       ...              ...
199  9926.HK          AKESO-B
200  9959.HK      LINKLOGIS-W
201  9969.HK       INNOCARE-B
202  9987.HK        YUM CHINA
203  9997.HK   KANGJI MEDICAL

[204 rows x 2 columns]

In [5]:
midcap_symbol= midcap_stock_ticker.Symbol.to_list()
print(midcap_symbol)

['0008.HK', '0013.HK', '0014.HK', '0019.HK', '0023.HK', '0123.HK', '0136.HK', '0144.HK', '0148.HK', '0152.HK', '0165.HK', '0168.HK', '0179.HK', '0189.HK', '0200.HK', '0220.HK', '0257.HK', '0293.HK', '0303.HK', '0336.HK', '0345.HK', '0354.HK', '0358.HK', '0371.HK', '0390.HK', '0392.HK', '0425.HK', '0460.HK', '0467.HK', '0489.HK', '0493.HK', '0512.HK', '0522.HK', '0535.HK', '0551.HK', '0558.HK', '0570.HK', '0586.HK', '0604.HK', '0631.HK', '0636.HK', '0659.HK', '0667.HK', '0670.HK', '0683.HK', '0696.HK', '0728.HK', '0753.HK', '0754.HK', '0763.HK', '0772.HK', '0778.HK', '0780.HK', '0788.HK', '0817.HK', '0839.HK', '0867.HK', '0873.HK', '0880.HK', '0884.HK', '0902.HK', '0909.HK', '0916.HK', '0966.HK', '0973.HK', '1030.HK', '1055.HK', '1060.HK', '1066.HK', '1099.HK', '1128.HK', '1171.HK', '1179.HK', '1199.HK', '1208.HK', '1238.HK', '1268.HK', '1310.HK', '1313.HK', '1316.HK', '1336.HK', '1339.HK', '1347.HK', '1359.HK', '1368.HK', '1458.HK', '1516.HK', '1530.HK', '1548.HK', '1579.HK', '1585.HK', '1691.HK', '1698.HK', '1717.HK', '1766.HK', '1772.HK', '1776.HK', '1800.HK', '1811.HK', '1813.HK', '1816.HK', '1833.HK', '1880.HK', '1882.HK', '1888.HK', '1898.HK', '1907.HK', '1908.HK', '1910.HK', '1919.HK', '1951.HK', '1988.HK', '1995.HK', '1999.HK', '2005.HK', '2013.HK', '2018.HK', '2039.HK', '2096.HK', '2128.HK', '2137.HK', '2150.HK', '2158.HK', '2160.HK', '2171.HK', '2186.HK', '2192.HK', '2196.HK', '2202.HK', '2238.HK', '2252.HK', '2282.HK', '2285.HK', '2314.HK', '2328.HK', '2338.HK', '2357.HK', '2359.HK', '2380.HK', '2400.HK', '2500.HK', '2518.HK', '2588.HK', '2607.HK', '2611.HK', '2669.HK', '2689.HK', '2772.HK', '2777.HK', '2778.HK', '2869.HK', '2899.HK', '3311.HK', '3319.HK', '3320.HK', '3323.HK', '3331.HK', '3360.HK', '3383.HK', '3396.HK', '3606.HK', '3633.HK', '3669.HK', '3759.HK', '3800.HK', '3808.HK', '3868.HK', '3888.HK', '3898.HK', '3899.HK', '3900.HK', '3908.HK', '3918.HK', '3990.HK', '3993.HK', '3998.HK', '6030.HK', '6060.HK', '6078.HK', '6110.HK', '6158.HK', '6185.HK', '6606.HK', '6699.HK', '6808.HK', '6818.HK', '6837.HK', '6881.HK', '6886.HK', '6993.HK', '9666.HK', '9688.HK', '9858.HK', '9863.HK', '9869.HK', '9899.HK', '9901.HK', '9922.HK', '9923.HK', '9926.HK', '9959.HK', '9969.HK', '9987.HK', '9997.HK']

In [6]:
#merging the two list together
for symbol in midcap_symbol:
    HSI_symbol.append(symbol)
    
HSI_symbol = list(dict.fromkeys(HSI_symbol))
print(HSI_symbol)

['0001.HK', '0002.HK', '0003.HK', '0005.HK', '0006.HK', '0011.HK', '0012.HK', '0016.HK', '0017.HK', '0027.HK', '0066.HK', '0101.HK', '0175.HK', '0241.HK', '0267.HK', '0288.HK', '0291.HK', '0316.HK', '0322.HK', '0386.HK', '0388.HK', '0669.HK', '0688.HK', '0700.HK', '0762.HK', '0823.HK', '0857.HK', '0868.HK', '0881.HK', '0883.HK', '0939.HK', '0941.HK', '0960.HK', '0968.HK', '0981.HK', '0992.HK', '1038.HK', '1044.HK', '1088.HK', '1093.HK', '1109.HK', '1113.HK', '1177.HK', '1209.HK', '1211.HK', '1299.HK', '1378.HK', '1398.HK', '1810.HK', '1876.HK', '1928.HK', '1929.HK', '1997.HK', '2007.HK', '2020.HK', '2269.HK', '2313.HK', '2318.HK', '2319.HK', '2331.HK', '2382.HK', '2388.HK', '2628.HK', '2688.HK', '3690.HK', '3692.HK', '3968.HK', '3988.HK', '6098.HK', '6690.HK', '6862.HK', '9618.HK', '9633.HK', '9988.HK', '9999.HK', '0008.HK', '0013.HK', '0014.HK', '0019.HK', '0023.HK', '0123.HK', '0136.HK', '0144.HK', '0148.HK', '0152.HK', '0165.HK', '0168.HK', '0179.HK', '0189.HK', '0200.HK', '0220.HK', '0257.HK', '0293.HK', '0303.HK', '0336.HK', '0345.HK', '0354.HK', '0358.HK', '0371.HK', '0390.HK', '0392.HK', '0425.HK', '0460.HK', '0467.HK', '0489.HK', '0493.HK', '0512.HK', '0522.HK', '0535.HK', '0551.HK', '0558.HK', '0570.HK', '0586.HK', '0604.HK', '0631.HK', '0636.HK', '0659.HK', '0667.HK', '0670.HK', '0683.HK', '0696.HK', '0728.HK', '0753.HK', '0754.HK', '0763.HK', '0772.HK', '0778.HK', '0780.HK', '0788.HK', '0817.HK', '0839.HK', '0867.HK', '0873.HK', '0880.HK', '0884.HK', '0902.HK', '0909.HK', '0916.HK', '0966.HK', '0973.HK', '1030.HK', '1055.HK', '1060.HK', '1066.HK', '1099.HK', '1128.HK', '1171.HK', '1179.HK', '1199.HK', '1208.HK', '1238.HK', '1268.HK', '1310.HK', '1313.HK', '1316.HK', '1336.HK', '1339.HK', '1347.HK', '1359.HK', '1368.HK', '1458.HK', '1516.HK', '1530.HK', '1548.HK', '1579.HK', '1585.HK', '1691.HK', '1698.HK', '1717.HK', '1766.HK', '1772.HK', '1776.HK', '1800.HK', '1811.HK', '1813.HK', '1816.HK', '1833.HK', '1880.HK', '1882.HK', '1888.HK', '1898.HK', '1907.HK', '1908.HK', '1910.HK', '1919.HK', '1951.HK', '1988.HK', '1995.HK', '1999.HK', '2005.HK', '2013.HK', '2018.HK', '2039.HK', '2096.HK', '2128.HK', '2137.HK', '2150.HK', '2158.HK', '2160.HK', '2171.HK', '2186.HK', '2192.HK', '2196.HK', '2202.HK', '2238.HK', '2252.HK', '2282.HK', '2285.HK', '2314.HK', '2328.HK', '2338.HK', '2357.HK', '2359.HK', '2380.HK', '2400.HK', '2500.HK', '2518.HK', '2588.HK', '2607.HK', '2611.HK', '2669.HK', '2689.HK', '2772.HK', '2777.HK', '2778.HK', '2869.HK', '2899.HK', '3311.HK', '3319.HK', '3320.HK', '3323.HK', '3331.HK', '3360.HK', '3383.HK', '3396.HK', '3606.HK', '3633.HK', '3669.HK', '3759.HK', '3800.HK', '3808.HK', '3868.HK', '3888.HK', '3898.HK', '3899.HK', '3900.HK', '3908.HK', '3918.HK', '3990.HK', '3993.HK', '3998.HK', '6030.HK', '6060.HK', '6078.HK', '6110.HK', '6158.HK', '6185.HK', '6606.HK', '6699.HK', '6808.HK', '6818.HK', '6837.HK', '6881.HK', '6886.HK', '6993.HK', '9666.HK', '9688.HK', '9858.HK', '9863.HK', '9869.HK', '9899.HK', '9901.HK', '9922.HK', '9923.HK', '9926.HK', '9959.HK', '9969.HK', '9987.HK', '9997.HK']

In [ ]:
len(HSI_symbol)

In [8]:
def getdata(tickers):
    data=[]
    for ticker in tickers:
        data.append(yf.download(ticker,period='5y').reset_index())
    return data

In [9]:
HK = getdata(HSI_symbol)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [10]:
HK

[           Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  97.250000  98.599998  97.050003  97.250000  77.971375
 1    2018-02-14  97.250000  97.900002  96.550003  97.849998  78.452431
 2    2018-02-15  98.000000  99.000000  98.000000  98.949997  79.334381
 3    2018-02-20  99.900002  99.900002  97.500000  97.849998  78.452431
 4    2018-02-21  98.150002  98.599998  97.250000  98.550003  79.013680
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  48.750000  49.200001  48.500000  48.549999  48.549999
 1226 2023-02-08  48.549999  49.700001  48.500000  48.900002  48.900002
 1227 2023-02-09  48.900002  49.450001  48.799999  49.349998  49.349998
 1228 2023-02-10  49.349998  50.099998  49.299999  49.450001  49.450001
 1229 2023-02-13  49.049999  49.349998  48.849998  49.000000  49.000000

        Volume
 0     5456296
 1     7572132
 2     3716540
 3     3753917
 4     4128242
 ...       ...
 1225  4581643
 1226  3595270
 1227  3099953
 1228  3632251
 1229  1541329

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  75.550003  76.000000  75.050003  75.349998  60.191566
 1    2018-02-14  75.349998  76.650002  75.349998  76.500000  61.110222
 2    2018-02-15  76.699997  76.699997  75.500000  76.000000  60.710800
 3    2018-02-20  77.099998  77.099998  75.849998  76.650002  61.230053
 4    2018-02-21  76.599998  77.000000  76.500000  76.750000  61.309925
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  58.000000  58.099998  57.400002  57.599998  57.599998
 1226 2023-02-08  57.400002  58.000000  57.400002  57.799999  57.799999
 1227 2023-02-09  57.950001  57.950001  57.400002  57.750000  57.750000
 1228 2023-02-10  57.799999  58.250000  57.500000  57.549999  57.549999
 1229 2023-02-13  57.500000  57.950001  57.099998  57.150002  57.150002

        Volume
 0     4884615
 1     3560475
 2     2533715
 3     2809124
 4     2554212
 ...       ...
 1225  2100111
 1226  1291202
 1227  1688222
 1228  1550687
 1229  1285555

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  11.019283  11.109237  11.019283  11.019283   9.599367
 1    2018-02-14  11.034275  11.124229  11.034275  11.124229   9.690787
 2    2018-02-15  11.094244  11.154213  11.049268  11.094244   9.664667
 3    2018-02-20  11.094244  11.379097  11.064260  11.334120   9.873636
 4    2018-02-21  11.349112  11.409081  11.289143  11.364104   9.899755
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07   7.790000   7.860000   7.660000   7.670000   7.670000
 1226 2023-02-08   7.670000   7.780000   7.670000   7.710000   7.710000
 1227 2023-02-09   7.670000   7.730000   7.650000   7.730000   7.730000
 1228 2023-02-10   7.670000   7.840000   7.670000   7.710000   7.710000
 1229 2023-02-13   7.700000   7.730000   7.560000   7.630000   7.630000

         Volume
 0     27649323
 1     18722763
 2     22508905
 3     33662121
 4     11931480
 ...        ...
 1225   9460154
 1226   9126394
 1227   8522806
 1228   9475489
 1229   8418986

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  79.599998  80.449997  79.599998  79.800003  65.257202
 1    2018-02-14  79.849998  82.199997  79.849998  81.900002  66.974495
 2    2018-02-15  83.000000  83.750000  82.699997  83.550003  68.323814
 3    2018-02-20  83.750000  85.000000  80.849998  80.949997  66.197609
 4    2018-02-21  81.500000  82.050003  80.699997  81.599998  66.729164
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  56.599998  57.000000  56.599998  56.599998  56.599998
 1226 2023-02-08  56.900002  58.099998  56.900002  57.799999  57.799999
 1227 2023-02-09  57.599998  58.000000  57.349998  58.000000  58.000000
 1228 2023-02-10  58.400002  58.450001  57.849998  58.000000  58.000000
 1229 2023-02-13  57.000000  57.700001  57.000000  57.599998  57.599998

         Volume
 0     29293870
 1     47649359
 2     36584847
 3     84846341
 4     52960544
 ...        ...
 1225   9938412
 1226  21470580
 1227  11986027
 1228  16892115
 1229   5571839

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  64.400002  64.900002  64.000000  64.199997  44.744080
 1    2018-02-14  64.500000  65.900002  64.199997  65.849998  45.894039
 2    2018-02-15  65.750000  66.250000  65.050003  66.099998  46.068279
 3    2018-02-20  66.000000  66.250000  65.099998  65.650002  45.754650
 4    2018-02-21  65.750000  65.949997  65.449997  65.550003  45.684959
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  44.349998  44.500000  43.599998  43.750000  43.750000
 1226 2023-02-08  43.750000  44.299999  43.500000  43.750000  43.750000
 1227 2023-02-09  43.750000  44.099998  43.549999  43.900002  43.900002
 1228 2023-02-10  43.549999  44.400002  43.549999  43.750000  43.750000
 1229 2023-02-13  43.799999  43.799999  43.150002  43.299999  43.299999

        Volume
 0     5535951
 1     9080768
 2     2832361
 3     4513412
 4     3155541
 ...       ...
 1225  1549239
 1226  1796456
 1227  1273655
 1228  1967615
 1229  1051516

 [1230 rows x 7 columns],
            Date        Open        High         Low       Close   Adj Close  \
 0    2018-02-13  176.000000  179.000000  176.000000  177.699997  146.420502
 1    2018-02-14  180.899994  191.899994  180.300003  191.500000  157.791351
 2    2018-02-15  191.000000  192.300003  188.199997  192.300003  158.450562
 3    2018-02-20  192.000000  193.399994  188.699997  189.199997  155.896240
 4    2018-02-21  191.000000  192.500000  189.699997  192.500000  158.615372
 ...         ...         ...         ...         ...         ...         ...
 1225 2023-02-07  124.699997  125.400002  123.800003  124.099998  124.099998
 1226 2023-02-08  123.800003  126.699997  123.800003  125.599998  125.599998
 1227 2023-02-09  125.500000  126.199997  124.500000  125.400002  125.400002
 1228 2023-02-10  124.599998  127.000000  124.599998  126.099998  126.099998
 1229 2023-02-13  126.000000  126.300003  124.900002  126.199997  126.199997

        Volume
 0     1377132
 1     4226140
 2     1756072
 3     2680405
 4     1778589
 ...       ...
 1225   763600
 1226   916757
 1227   841932
 1228   818721
 1229   420164

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  40.950413  41.239670  40.867767  40.991734  31.115879
 1    2018-02-14  41.115704  41.280991  40.702480  41.115704  31.209982
 2    2018-02-15  41.322315  41.487602  40.950413  41.404957  31.429548
 3    2018-02-20  41.404957  41.735538  40.909088  41.198345  31.272711
 4    2018-02-21  41.239670  41.735538  41.115704  41.694214  31.649117
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  28.950001  29.049999  28.500000  28.750000  28.750000
 1226 2023-02-08  28.600000  29.100000  28.200001  28.799999  28.799999
 1227 2023-02-09  28.450001  29.150000  28.450001  28.950001  28.950001
 1228 2023-02-10  28.900000  29.500000  28.900000  29.200001  29.200001
 1229 2023-02-13  28.750000  28.750000  27.600000  27.700001  27.700001

        Volume
 0     6182599
 1     6532095
 2     2751881
 3     3466438
 4     5826156
 ...       ...
 1225  1357100
 1226  2191699
 1227  1807496
 1228  1412482
 1229  2507841

 [1230 rows x 7 columns],
            Date        Open        High         Low       Close   Adj Close  \
 0    2018-02-13  122.800003  123.900002  122.000000  122.500000   93.012627
 1    2018-02-14  124.000000  126.199997  122.500000  126.000000   95.670135
 2    2018-02-15  125.500000  126.599998  125.199997  125.500000   95.290482
 3    2018-02-20  126.500000  127.699997  124.500000  126.800003   96.277557
 4    2018-02-21  127.199997  128.000000  126.099998  127.400002   96.733116
 ...         ...         ...         ...         ...         ...         ...
 1225 2023-02-07  112.199997  112.400002  109.900002  110.500000  110.500000
 1226 2023-02-08  110.699997  112.500000  110.699997  112.300003  112.300003
 1227 2023-02-09  111.500000  112.099998  110.599998  112.000000  112.000000
 1228 2023-02-10  111.300003  113.199997  111.300003  112.000000  112.000000
 1229 2023-02-13  109.900002  110.199997  108.300003  108.500000  108.500000

        Volume
 0     3833533
 1     3365550
 2     2921100
 3     2755692
 4     2089403
 ...       ...
 1225  2877239
 1226  2927696
 1227  1535021
 1228  1451890
 1229  2592529

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  44.959999  46.240002  44.959999  45.360001  33.563492
 1    2018-02-14  45.360001  46.480000  45.040001  46.400002  34.333019
 2    2018-02-15  46.480000  46.720001  45.840000  46.480000  34.392216
 3    2018-02-20  46.799999  47.040001  45.840000  46.240002  34.214634
 4    2018-02-21  46.240002  46.880001  46.000000  46.639999  34.510612
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  23.500000  23.950001  23.500000  23.549999  23.549999
 1226 2023-02-08  23.549999  24.450001  23.500000  24.000000  24.000000
 1227 2023-02-09  23.950001  24.299999  23.850000  24.250000  24.250000
 1228 2023-02-10  24.000000  24.200001  23.700001  23.950001  23.950001
 1229 2023-02-13  23.400000  23.400000  21.650000  22.200001  22.200001

         Volume
 0      4825360
 1      4241130
 2      2326302
 3      2495116
 4      2908687
 ...        ...
 1225   3498528
 1226   5554918
 1227   2359533
 1228   4208697
 1229  12238450

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  62.200001  64.550003  62.200001  64.500000  61.371941
 1    2018-02-14  64.150002  65.650002  63.599998  65.650002  62.466167
 2    2018-02-15  67.000000  67.150002  66.050003  66.699997  63.465244
 3    2018-02-20  66.800003  68.000000  66.150002  68.000000  64.702202
 4    2018-02-21  68.000000  68.199997  67.150002  67.949997  64.654633
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  54.450001  54.549999  52.799999  52.849998  52.849998
 1226 2023-02-08  52.849998  53.500000  52.700001  52.700001  52.700001
 1227 2023-02-09  52.700001  54.400002  52.700001  54.400002  54.400002
 1228 2023-02-10  54.049999  55.200001  53.849998  53.849998  53.849998
 1229 2023-02-13  54.500000  54.500000  52.700001  53.900002  53.900002

         Volume
 0     16508540
 1     10297214
 2      9660048
 3     14738503
 4      8154710
 ...        ...
 1225  10255598
 1226   5761853
 1227   6683660
 1228   4052977
 1229   2020239

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  40.599998  41.049999  40.599998  40.750000  35.357822
 1    2018-02-14  40.799999  40.900002  40.599998  40.599998  35.227673
 2    2018-02-15  40.799999  40.900002  40.750000  40.900002  35.487980
 3    2018-02-20  40.900002  41.450001  40.900002  41.250000  35.791664
 4    2018-02-21  41.049999  41.599998  41.000000  41.599998  36.095348
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  41.849998  41.900002  41.250000  41.599998  41.599998
 1226 2023-02-08  41.349998  42.000000  41.349998  41.799999  41.799999
 1227 2023-02-09  41.799999  41.799999  41.400002  41.700001  41.700001
 1228 2023-02-10  41.500000  41.950001  41.400002  41.549999  41.549999
 1229 2023-02-13  41.450001  41.849998  41.099998  41.250000  41.250000

        Volume
 0     6641120
 1     9112034
 2     2734535
 3     7340524
 4     4309160
 ...       ...
 1225  1629150
 1226  1517284
 1227  1457946
 1228  1702004
 1229   800878

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  18.420000  18.820000  18.320000  18.500000  14.853987
 1    2018-02-14  18.620001  18.660000  18.320000  18.540001  14.886102
 2    2018-02-15  18.440001  18.620001  18.379999  18.620001  14.950336
 3    2018-02-20  18.680000  18.700001  18.180000  18.379999  14.757637
 4    2018-02-21  18.400000  18.860001  18.299999  18.860001  15.143035
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  15.760000  15.940000  15.580000  15.800000  15.800000
 1226 2023-02-08  15.820000  15.920000  15.720000  15.780000  15.780000
 1227 2023-02-09  15.680000  15.980000  15.680000  15.920000  15.920000
 1228 2023-02-10  15.820000  16.200001  15.820000  15.980000  15.980000
 1229 2023-02-13  15.900000  15.900000  15.400000  15.540000  15.540000

        Volume
 0     5796393
 1     6158928
 2     4953199
 3     8098243
 4     4328611
 ...       ...
 1225  4237255
 1226  3390841
 1227  7898211
 1228  2406280
 1229  2094018

 [1230 rows x 7 columns],
            Date       Open       High    Low      Close  Adj Close    Volume
 0    2018-02-13  22.600000  22.799999  22.15  22.400000  20.568617  41405088
 1    2018-02-14  22.750000  22.750000  22.10  22.500000  20.660440  29125755
 2    2018-02-15  22.799999  23.000000  22.60  22.700001  20.844091  23214896
 3    2018-02-20  23.250000  23.799999  22.75  23.250000  21.349123  54404126
 4    2018-02-21  23.400000  23.799999  23.15  23.750000  21.808245  34773917
 ...         ...        ...        ...    ...        ...        ...       ...
 1225 2023-02-07  12.200000  12.360000  12.02  12.080000  12.080000  39431286
 1226 2023-02-08  12.000000  12.080000  11.64  11.760000  11.760000  60013636
 1227 2023-02-09  11.760000  12.020000  11.72  12.020000  12.020000  39442435
 1228 2023-02-10  11.940000  11.980000  11.60  11.620000  11.620000  42001117
 1229 2023-02-13  11.540000  11.660000  11.26  11.620000  11.620000  39868669

 [1230 rows x 7 columns],
            Date  Open  High   Low  Close  Adj Close     Volume
 0    2018-02-13  3.69  3.77  3.69   3.70       3.70    3822000
 1    2018-02-14  3.70  3.75  3.70   3.72       3.72    2198000
 2    2018-02-15  3.80  3.92  3.72   3.84       3.84    4362000
 3    2018-02-20  3.84  3.90  3.80   3.84       3.84    3912000
 4    2018-02-21  3.82  3.89  3.82   3.89       3.89    3402000
 ...         ...   ...   ...   ...    ...        ...        ...
 1225 2023-02-07  6.36  6.51  6.29   6.34       6.34   61000933
 1226 2023-02-08  6.34  6.34  5.96   6.11       6.11  104128634
 1227 2023-02-09  6.00  6.40  6.00   6.38       6.38   68845686
 1228 2023-02-10  6.21  6.35  5.95   6.05       6.05   77784826
 1229 2023-02-13  5.93  6.09  5.82   6.07       6.07   34826893

 [1230 rows x 7 columns],
            Date   Open   High    Low  Close  Adj Close    Volume
 0    2018-02-13  10.92  11.00  10.80  10.90   8.079907  10482192
 1    2018-02-14  10.80  11.12  10.80  11.08   8.213338  12817735
 2    2018-02-15  11.10  11.24  11.00  11.14   8.257816   6776269
 3    2018-02-20  11.26  11.32  10.98  11.22   8.317117  10004054
 4    2018-02-21  11.32  11.40  11.16  11.40   8.450546   9177632
 ...         ...    ...    ...    ...    ...        ...       ...
 1225 2023-02-07   8.98   9.07   8.93   8.96   8.960000   5541708
 1226 2023-02-08   8.89   9.26   8.89   9.17   9.170000   7624990
 1227 2023-02-09   9.12   9.20   9.08   9.12   9.120000   4406059
 1228 2023-02-10   9.07   9.22   9.05   9.13   9.130000   4602059
 1229 2023-02-13   9.03   9.15   9.02   9.06   9.060000   2439243

 [1230 rows x 7 columns],
            Date  Open  High   Low  Close  Adj Close    Volume
 0    2018-02-13  8.83  9.12  8.75   9.10   7.680335  43812420
 1    2018-02-14  9.00  9.19  9.00   9.05   7.638136  21279822
 2    2018-02-15  9.10  9.18  8.90   8.99   7.587497  19217457
 3    2018-02-20  9.10  9.11  8.84   9.05   7.638136  36525174
 4    2018-02-21  9.10  9.36  9.09   9.35   7.891334  19184126
 ...         ...   ...   ...   ...    ...        ...       ...
 1225 2023-02-07  4.73  4.75  4.67   4.68   4.680000  11324949
 1226 2023-02-08  4.72  4.78  4.69   4.74   4.740000  17147502
 1227 2023-02-09  4.70  4.76  4.69   4.75   4.750000  17303134
 1228 2023-02-10  4.70  4.81  4.69   4.71   4.710000  20259688
 1229 2023-02-13  4.71  4.72  4.66   4.69   4.690000   5838071

 [1230 rows x 7 columns],
            Date       Open       High        Low      Close  Adj Close  \
 0    2018-02-13  29.000000  29.799999  29.000000  29.200001  28.241522
 1    2018-02-14  29.850000  29.850000  29.049999  29.350000  28.386600
 2    2018-02-15  29.850000  29.950001  29.549999  29.700001  28.725109
 3    2018-02-20  29.750000  30.100000  29.049999  29.850000  28.870184
 4    2018-02-21  30.200001  30.549999  29.750000  30.500000  29.498848
 ...         ...        ...        ...        ...        ...        ...
 1225 2023-02-07  56.950001  58.549999  56.950001  57.500000  57.500000
 1226 2023-02-08  58.000000  58.000000  56.500000  57.000000  57.000000
 1227 2023-02-09  56.599998  59.200001  56.599998  59.000000  59.000000
 1228 2023-02-10  58.849998  59.200001  58.000000  58.000000  58.000000
 1229 2023-02-13  57.349998  61.150002  57.250000  60.950001  60.950001

        Volume
 0     6583727
 1     1512674
 2     2344474
 3     4618427
 4     5683847
 ...       ...
 1225  4559041
 1226  3243418
 1227  5812478
 1228  5562095
 1229  5844760

 [1230 rows x 7 columns],
            Date        Open        High         Low       Close   Adj Close  \
 0    2018-02-13   72.500000   72.599998   72.199997   72.250000   37.676903
 1    2018-02-14   72.250000   72.900002   72.250000   72.800003   37.963715
 2    2018-02-15   72.800003   72.849998   72.550003   72.599998   37.859428
 3    2018-02-20   72.000000   74.099998   72.000000   74.099998   38.641647
 4    2018-02-21   73.750000   74.000000   73.300003   73.300003   38.224461
 ...         ...         ...         ...         ...         ...         ...
 1225 2023-02-07  135.100006  137.699997  134.500000  137.199997  137.199997
 1226 2023-02-08  137.199997  141.199997  137.199997  139.899994  139.899994
 1227 2023-02-09  140.000000  140.899994  138.000000  139.199997  139.199997
 1228 2023-02-10  138.500000  139.699997  136.000000  136.899994  136.899994
 1229 2023-02-13  135.399994  136.000000  132.399994  132.399994  132.399994

        Volume
 0      383000
 1      495662
 2      561699
 3      714290
 4      669225
 ...       ...
 1225   709628
 1226  1058787
 1227   497755
 1228   503500
 1229   615987

 [1230 rows x 7 columns],
            Date   Open   High    Low  Close  Adj Close   Volume
 0    2018-02-13  14.72  15.36  14.60  15.20  12.492501  7185319
 1    2018-02-14  15.10  15.46  15.02  15.46  12.706189  3741667
 2    2018-02-15  15.66  15.66  15.16  15.30  12.574689  1723325
 3    2018-02-20  15.50  15.94  15.34  15.70  12.903440  4623200
 4    2018-02-21  15.72  15.72  15.24  15.70  12.903440  3876001
 ...         ...    ...    ...    ...    ...        ...      ...
 1225 2023-02-07  13.10  13.10  12.96  13.04  13.040000  8811258
 1226 2023-02-08  13.02  13.10  12.76  12.78  12.780000  5529098
 1227 2023-02-09  12.74  12.88  12.68  12.80  12.800000  7291722
 1228 2023-02-10  12.78  12.88  12.64  12.72  12.720000  6389600
 1229 2023-02-13  12.88  12.96  12.60  12.94  12.940000  2331044

 [1230 rows x 7 columns],
            Date  Open  High   Low  Close  Adj Close     Volume
 0    2018-02-13  6.06  6.19  5.98   5.99   3.678946  162556514
 1    2018-02-14  6.04  6.15  5.95   6.10   3.746505  132012367
 2    2018-02-15  6.20  6.36  6.14   6.27   3.850917  134937761
 3    2018-02-20  6.15  6.31  6.15   6.19   3.801782   69764789
 4    2018-02-21  6.34  6.47  6.24   6.42   3.943043  101780382
 ...         ...   ...   ...   ...    ...        ...        ...
 1225 2023-02-07  4.12  4.24  4.12   4.15   4.150000   78692555

In [11]:
#Assigning symbol into each stock list
for i in range(len(HK)):
    HK[i]['Symbol']= HSI_symbol[i]
print(HK)

[           Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  97.250000  98.599998  97.050003  97.250000  77.971375
1    2018-02-14  97.250000  97.900002  96.550003  97.849998  78.452431
2    2018-02-15  98.000000  99.000000  98.000000  98.949997  79.334381
3    2018-02-20  99.900002  99.900002  97.500000  97.849998  78.452431
4    2018-02-21  98.150002  98.599998  97.250000  98.550003  79.013680
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  48.750000  49.200001  48.500000  48.549999  48.549999
1226 2023-02-08  48.549999  49.700001  48.500000  48.900002  48.900002
1227 2023-02-09  48.900002  49.450001  48.799999  49.349998  49.349998
1228 2023-02-10  49.349998  50.099998  49.299999  49.450001  49.450001
1229 2023-02-13  49.049999  49.349998  48.849998  49.000000  49.000000

       Volume   Symbol
0     5456296  0001.HK
1     7572132  0001.HK
2     3716540  0001.HK
3     3753917  0001.HK
4     4128242  0001.HK
...       ...      ...
1225  4581643  0001.HK
1226  3595270  0001.HK
1227  3099953  0001.HK
1228  3632251  0001.HK
1229  1541329  0001.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  75.550003  76.000000  75.050003  75.349998  60.191566
1    2018-02-14  75.349998  76.650002  75.349998  76.500000  61.110222
2    2018-02-15  76.699997  76.699997  75.500000  76.000000  60.710800
3    2018-02-20  77.099998  77.099998  75.849998  76.650002  61.230053
4    2018-02-21  76.599998  77.000000  76.500000  76.750000  61.309925
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  58.000000  58.099998  57.400002  57.599998  57.599998
1226 2023-02-08  57.400002  58.000000  57.400002  57.799999  57.799999
1227 2023-02-09  57.950001  57.950001  57.400002  57.750000  57.750000
1228 2023-02-10  57.799999  58.250000  57.500000  57.549999  57.549999
1229 2023-02-13  57.500000  57.950001  57.099998  57.150002  57.150002

       Volume   Symbol
0     4884615  0002.HK
1     3560475  0002.HK
2     2533715  0002.HK
3     2809124  0002.HK
4     2554212  0002.HK
...       ...      ...
1225  2100111  0002.HK
1226  1291202  0002.HK
1227  1688222  0002.HK
1228  1550687  0002.HK
1229  1285555  0002.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  11.019283  11.109237  11.019283  11.019283   9.599367
1    2018-02-14  11.034275  11.124229  11.034275  11.124229   9.690787
2    2018-02-15  11.094244  11.154213  11.049268  11.094244   9.664667
3    2018-02-20  11.094244  11.379097  11.064260  11.334120   9.873636
4    2018-02-21  11.349112  11.409081  11.289143  11.364104   9.899755
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07   7.790000   7.860000   7.660000   7.670000   7.670000
1226 2023-02-08   7.670000   7.780000   7.670000   7.710000   7.710000
1227 2023-02-09   7.670000   7.730000   7.650000   7.730000   7.730000
1228 2023-02-10   7.670000   7.840000   7.670000   7.710000   7.710000
1229 2023-02-13   7.700000   7.730000   7.560000   7.630000   7.630000

        Volume   Symbol
0     27649323  0003.HK
1     18722763  0003.HK
2     22508905  0003.HK
3     33662121  0003.HK
4     11931480  0003.HK
...        ...      ...
1225   9460154  0003.HK
1226   9126394  0003.HK
1227   8522806  0003.HK
1228   9475489  0003.HK
1229   8418986  0003.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  79.599998  80.449997  79.599998  79.800003  65.257202
1    2018-02-14  79.849998  82.199997  79.849998  81.900002  66.974495
2    2018-02-15  83.000000  83.750000  82.699997  83.550003  68.323814
3    2018-02-20  83.750000  85.000000  80.849998  80.949997  66.197609
4    2018-02-21  81.500000  82.050003  80.699997  81.599998  66.729164
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  56.599998  57.000000  56.599998  56.599998  56.599998
1226 2023-02-08  56.900002  58.099998  56.900002  57.799999  57.799999
1227 2023-02-09  57.599998  58.000000  57.349998  58.000000  58.000000
1228 2023-02-10  58.400002  58.450001  57.849998  58.000000  58.000000
1229 2023-02-13  57.000000  57.700001  57.000000  57.599998  57.599998

        Volume   Symbol
0     29293870  0005.HK
1     47649359  0005.HK
2     36584847  0005.HK
3     84846341  0005.HK
4     52960544  0005.HK
...        ...      ...
1225   9938412  0005.HK
1226  21470580  0005.HK
1227  11986027  0005.HK
1228  16892115  0005.HK
1229   5571839  0005.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  64.400002  64.900002  64.000000  64.199997  44.744080
1    2018-02-14  64.500000  65.900002  64.199997  65.849998  45.894039
2    2018-02-15  65.750000  66.250000  65.050003  66.099998  46.068279
3    2018-02-20  66.000000  66.250000  65.099998  65.650002  45.754650
4    2018-02-21  65.750000  65.949997  65.449997  65.550003  45.684959
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  44.349998  44.500000  43.599998  43.750000  43.750000
1226 2023-02-08  43.750000  44.299999  43.500000  43.750000  43.750000
1227 2023-02-09  43.750000  44.099998  43.549999  43.900002  43.900002
1228 2023-02-10  43.549999  44.400002  43.549999  43.750000  43.750000
1229 2023-02-13  43.799999  43.799999  43.150002  43.299999  43.299999

       Volume   Symbol
0     5535951  0006.HK
1     9080768  0006.HK
2     2832361  0006.HK
3     4513412  0006.HK
4     3155541  0006.HK
...       ...      ...
1225  1549239  0006.HK
1226  1796456  0006.HK
1227  1273655  0006.HK
1228  1967615  0006.HK
1229  1051516  0006.HK

[1230 rows x 8 columns],            Date        Open        High         Low       Close   Adj Close  \
0    2018-02-13  176.000000  179.000000  176.000000  177.699997  146.420502
1    2018-02-14  180.899994  191.899994  180.300003  191.500000  157.791351
2    2018-02-15  191.000000  192.300003  188.199997  192.300003  158.450562
3    2018-02-20  192.000000  193.399994  188.699997  189.199997  155.896240
4    2018-02-21  191.000000  192.500000  189.699997  192.500000  158.615372
...         ...         ...         ...         ...         ...         ...
1225 2023-02-07  124.699997  125.400002  123.800003  124.099998  124.099998
1226 2023-02-08  123.800003  126.699997  123.800003  125.599998  125.599998
1227 2023-02-09  125.500000  126.199997  124.500000  125.400002  125.400002
1228 2023-02-10  124.599998  127.000000  124.599998  126.099998  126.099998
1229 2023-02-13  126.000000  126.300003  124.900002  126.199997  126.199997

       Volume   Symbol
0     1377132  0011.HK
1     4226140  0011.HK
2     1756072  0011.HK
3     2680405  0011.HK
4     1778589  0011.HK
...       ...      ...
1225   763600  0011.HK
1226   916757  0011.HK
1227   841932  0011.HK
1228   818721  0011.HK
1229   420164  0011.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  40.950413  41.239670  40.867767  40.991734  31.115879
1    2018-02-14  41.115704  41.280991  40.702480  41.115704  31.209982
2    2018-02-15  41.322315  41.487602  40.950413  41.404957  31.429548
3    2018-02-20  41.404957  41.735538  40.909088  41.198345  31.272711
4    2018-02-21  41.239670  41.735538  41.115704  41.694214  31.649117
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  28.950001  29.049999  28.500000  28.750000  28.750000
1226 2023-02-08  28.600000  29.100000  28.200001  28.799999  28.799999
1227 2023-02-09  28.450001  29.150000  28.450001  28.950001  28.950001
1228 2023-02-10  28.900000  29.500000  28.900000  29.200001  29.200001
1229 2023-02-13  28.750000  28.750000  27.600000  27.700001  27.700001

       Volume   Symbol
0     6182599  0012.HK
1     6532095  0012.HK
2     2751881  0012.HK
3     3466438  0012.HK
4     5826156  0012.HK
...       ...      ...
1225  1357100  0012.HK
1226  2191699  0012.HK
1227  1807496  0012.HK
1228  1412482  0012.HK
1229  2507841  0012.HK

[1230 rows x 8 columns],            Date        Open        High         Low       Close   Adj Close  \
0    2018-02-13  122.800003  123.900002  122.000000  122.500000   93.012627
1    2018-02-14  124.000000  126.199997  122.500000  126.000000   95.670135
2    2018-02-15  125.500000  126.599998  125.199997  125.500000   95.290482
3    2018-02-20  126.500000  127.699997  124.500000  126.800003   96.277557
4    2018-02-21  127.199997  128.000000  126.099998  127.400002   96.733116
...         ...         ...         ...         ...         ...         ...
1225 2023-02-07  112.199997  112.400002  109.900002  110.500000  110.500000
1226 2023-02-08  110.699997  112.500000  110.699997  112.300003  112.300003
1227 2023-02-09  111.500000  112.099998  110.599998  112.000000  112.000000
1228 2023-02-10  111.300003  113.199997  111.300003  112.000000  112.000000
1229 2023-02-13  109.900002  110.199997  108.300003  108.500000  108.500000

       Volume   Symbol
0     3833533  0016.HK
1     3365550  0016.HK
2     2921100  0016.HK
3     2755692  0016.HK
4     2089403  0016.HK
...       ...      ...
1225  2877239  0016.HK
1226  2927696  0016.HK
1227  1535021  0016.HK
1228  1451890  0016.HK
1229  2592529  0016.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  44.959999  46.240002  44.959999  45.360001  33.563492
1    2018-02-14  45.360001  46.480000  45.040001  46.400002  34.333019
2    2018-02-15  46.480000  46.720001  45.840000  46.480000  34.392216
3    2018-02-20  46.799999  47.040001  45.840000  46.240002  34.214634
4    2018-02-21  46.240002  46.880001  46.000000  46.639999  34.510612
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  23.500000  23.950001  23.500000  23.549999  23.549999
1226 2023-02-08  23.549999  24.450001  23.500000  24.000000  24.000000
1227 2023-02-09  23.950001  24.299999  23.850000  24.250000  24.250000
1228 2023-02-10  24.000000  24.200001  23.700001  23.950001  23.950001
1229 2023-02-13  23.400000  23.400000  21.650000  22.200001  22.200001

        Volume   Symbol
0      4825360  0017.HK
1      4241130  0017.HK
2      2326302  0017.HK
3      2495116  0017.HK
4      2908687  0017.HK
...        ...      ...
1225   3498528  0017.HK
1226   5554918  0017.HK
1227   2359533  0017.HK
1228   4208697  0017.HK
1229  12238450  0017.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  62.200001  64.550003  62.200001  64.500000  61.371941
1    2018-02-14  64.150002  65.650002  63.599998  65.650002  62.466167
2    2018-02-15  67.000000  67.150002  66.050003  66.699997  63.465244
3    2018-02-20  66.800003  68.000000  66.150002  68.000000  64.702202
4    2018-02-21  68.000000  68.199997  67.150002  67.949997  64.654633
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  54.450001  54.549999  52.799999  52.849998  52.849998
1226 2023-02-08  52.849998  53.500000  52.700001  52.700001  52.700001
1227 2023-02-09  52.700001  54.400002  52.700001  54.400002  54.400002
1228 2023-02-10  54.049999  55.200001  53.849998  53.849998  53.849998
1229 2023-02-13  54.500000  54.500000  52.700001  53.900002  53.900002

        Volume   Symbol
0     16508540  0027.HK
1     10297214  0027.HK
2      9660048  0027.HK
3     14738503  0027.HK
4      8154710  0027.HK
...        ...      ...
1225  10255598  0027.HK
1226   5761853  0027.HK
1227   6683660  0027.HK
1228   4052977  0027.HK
1229   2020239  0027.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  40.599998  41.049999  40.599998  40.750000  35.357822
1    2018-02-14  40.799999  40.900002  40.599998  40.599998  35.227673
2    2018-02-15  40.799999  40.900002  40.750000  40.900002  35.487980
3    2018-02-20  40.900002  41.450001  40.900002  41.250000  35.791664
4    2018-02-21  41.049999  41.599998  41.000000  41.599998  36.095348
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  41.849998  41.900002  41.250000  41.599998  41.599998
1226 2023-02-08  41.349998  42.000000  41.349998  41.799999  41.799999
1227 2023-02-09  41.799999  41.799999  41.400002  41.700001  41.700001
1228 2023-02-10  41.500000  41.950001  41.400002  41.549999  41.549999
1229 2023-02-13  41.450001  41.849998  41.099998  41.250000  41.250000

       Volume   Symbol
0     6641120  0066.HK
1     9112034  0066.HK
2     2734535  0066.HK
3     7340524  0066.HK
4     4309160  0066.HK
...       ...      ...
1225  1629150  0066.HK
1226  1517284  0066.HK
1227  1457946  0066.HK
1228  1702004  0066.HK
1229   800878  0066.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  18.420000  18.820000  18.320000  18.500000  14.853987
1    2018-02-14  18.620001  18.660000  18.320000  18.540001  14.886102
2    2018-02-15  18.440001  18.620001  18.379999  18.620001  14.950336
3    2018-02-20  18.680000  18.700001  18.180000  18.379999  14.757637
4    2018-02-21  18.400000  18.860001  18.299999  18.860001  15.143035
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  15.760000  15.940000  15.580000  15.800000  15.800000
1226 2023-02-08  15.820000  15.920000  15.720000  15.780000  15.780000
1227 2023-02-09  15.680000  15.980000  15.680000  15.920000  15.920000
1228 2023-02-10  15.820000  16.200001  15.820000  15.980000  15.980000
1229 2023-02-13  15.900000  15.900000  15.400000  15.540000  15.540000

       Volume   Symbol
0     5796393  0101.HK
1     6158928  0101.HK
2     4953199  0101.HK
3     8098243  0101.HK
4     4328611  0101.HK
...       ...      ...
1225  4237255  0101.HK
1226  3390841  0101.HK
1227  7898211  0101.HK
1228  2406280  0101.HK
1229  2094018  0101.HK

[1230 rows x 8 columns],            Date       Open       High    Low      Close  Adj Close    Volume  \
0    2018-02-13  22.600000  22.799999  22.15  22.400000  20.568617  41405088
1    2018-02-14  22.750000  22.750000  22.10  22.500000  20.660440  29125755
2    2018-02-15  22.799999  23.000000  22.60  22.700001  20.844091  23214896
3    2018-02-20  23.250000  23.799999  22.75  23.250000  21.349123  54404126
4    2018-02-21  23.400000  23.799999  23.15  23.750000  21.808245  34773917
...         ...        ...        ...    ...        ...        ...       ...
1225 2023-02-07  12.200000  12.360000  12.02  12.080000  12.080000  39431286
1226 2023-02-08  12.000000  12.080000  11.64  11.760000  11.760000  60013636
1227 2023-02-09  11.760000  12.020000  11.72  12.020000  12.020000  39442435
1228 2023-02-10  11.940000  11.980000  11.60  11.620000  11.620000  42001117
1229 2023-02-13  11.540000  11.660000  11.26  11.620000  11.620000  39868669

       Symbol
0     0175.HK
1     0175.HK
2     0175.HK
3     0175.HK
4     0175.HK
...       ...
1225  0175.HK
1226  0175.HK
1227  0175.HK
1228  0175.HK
1229  0175.HK

[1230 rows x 8 columns],            Date  Open  High   Low  Close  Adj Close     Volume   Symbol
0    2018-02-13  3.69  3.77  3.69   3.70       3.70    3822000  0241.HK
1    2018-02-14  3.70  3.75  3.70   3.72       3.72    2198000  0241.HK
2    2018-02-15  3.80  3.92  3.72   3.84       3.84    4362000  0241.HK
3    2018-02-20  3.84  3.90  3.80   3.84       3.84    3912000  0241.HK
4    2018-02-21  3.82  3.89  3.82   3.89       3.89    3402000  0241.HK
...         ...   ...   ...   ...    ...        ...        ...      ...
1225 2023-02-07  6.36  6.51  6.29   6.34       6.34   61000933  0241.HK
1226 2023-02-08  6.34  6.34  5.96   6.11       6.11  104128634  0241.HK
1227 2023-02-09  6.00  6.40  6.00   6.38       6.38   68845686  0241.HK
1228 2023-02-10  6.21  6.35  5.95   6.05       6.05   77784826  0241.HK
1229 2023-02-13  5.93  6.09  5.82   6.07       6.07   34826893  0241.HK

[1230 rows x 8 columns],            Date   Open   High    Low  Close  Adj Close    Volume   Symbol
0    2018-02-13  10.92  11.00  10.80  10.90   8.079907  10482192  0267.HK
1    2018-02-14  10.80  11.12  10.80  11.08   8.213338  12817735  0267.HK
2    2018-02-15  11.10  11.24  11.00  11.14   8.257816   6776269  0267.HK
3    2018-02-20  11.26  11.32  10.98  11.22   8.317117  10004054  0267.HK
4    2018-02-21  11.32  11.40  11.16  11.40   8.450546   9177632  0267.HK
...         ...    ...    ...    ...    ...        ...       ...      ...
1225 2023-02-07   8.98   9.07   8.93   8.96   8.960000   5541708  0267.HK
1226 2023-02-08   8.89   9.26   8.89   9.17   9.170000   7624990  0267.HK
1227 2023-02-09   9.12   9.20   9.08   9.12   9.120000   4406059  0267.HK
1228 2023-02-10   9.07   9.22   9.05   9.13   9.130000   4602059  0267.HK
1229 2023-02-13   9.03   9.15   9.02   9.06   9.060000   2439243  0267.HK

[1230 rows x 8 columns],            Date  Open  High   Low  Close  Adj Close    Volume   Symbol
0    2018-02-13  8.83  9.12  8.75   9.10   7.680335  43812420  0288.HK
1    2018-02-14  9.00  9.19  9.00   9.05   7.638136  21279822  0288.HK
2    2018-02-15  9.10  9.18  8.90   8.99   7.587497  19217457  0288.HK
3    2018-02-20  9.10  9.11  8.84   9.05   7.638136  36525174  0288.HK
4    2018-02-21  9.10  9.36  9.09   9.35   7.891334  19184126  0288.HK
...         ...   ...   ...   ...    ...        ...       ...      ...
1225 2023-02-07  4.73  4.75  4.67   4.68   4.680000  11324949  0288.HK
1226 2023-02-08  4.72  4.78  4.69   4.74   4.740000  17147502  0288.HK
1227 2023-02-09  4.70  4.76  4.69   4.75   4.750000  17303134  0288.HK
1228 2023-02-10  4.70  4.81  4.69   4.71   4.710000  20259688  0288.HK
1229 2023-02-13  4.71  4.72  4.66   4.69   4.690000   5838071  0288.HK

[1230 rows x 8 columns],            Date       Open       High        Low      Close  Adj Close  \
0    2018-02-13  29.000000  29.799999  29.000000  29.200001  28.241522
1    2018-02-14  29.850000  29.850000  29.049999  29.350000  28.386600
2    2018-02-15  29.850000  29.950001  29.549999  29.700001  28.725109
3    2018-02-20  29.750000  30.100000  29.049999  29.850000  28.870184
4    2018-02-21  30.200001  30.549999  29.750000  30.500000  29.498848
...         ...        ...        ...        ...        ...        ...
1225 2023-02-07  56.950001  58.549999  56.950001  57.500000  57.500000
1226 2023-02-08  58.000000  58.000000  56.500000  57.000000  57.000000
1227 2023-02-09  56.599998  59.200001  56.599998  59.000000  59.000000
1228 2023-02-10  58.849998  59.200001  58.000000  58.000000  58.000000
1229 2023-02-13  57.349998  61.150002  57.250000  60.950001  60.950001

       Volume   Symbol
0     6583727  0291.HK
1     1512674  0291.HK
2     2344474  0291.HK
3     4618427  0291.HK
4     5683847  0291.HK
...       ...      ...
1225  4559041  0291.HK
1226  3243418  0291.HK
1227  5812478  0291.HK
1228  5562095  0291.HK
1229  5844760  0291.HK

[1230 rows x 8 columns],            Date        Open        High         Low       Close   Adj Close  \
0    2018-02-13   72.500000   72.599998   72.199997   72.250000   37.676903
1    2018-02-14   72.250000   72.900002   72.250000   72.800003   37.963715
2    2018-02-15   72.800003   72.849998   72.550003   72.599998   37.859428
3    2018-02-20   72.000000   74.099998   72.000000   74.099998   38.641647
4    2018-02-21   73.750000   74.000000   73.300003   73.300003   38.224461
...         ...         ...         ...         ...         ...         ...
1225 2023-02-07  135.100006  137.699997  134.500000  137.199997  137.199997
1226 2023-02-08  137.199997  141.199997  137.199997  139.899994  139.899994
1227 2023-02-09  140.000000  140.899994  138.000000  139.199997  139.199997
1228 2023-02-10  138.500000  139.699997  136.000000  136.899994  136.899994
1229 2023-02-13  135.399994  136.000000  132.399994  132.399994  132.399994

       Volume   Symbol
0      383000  0316.HK

In [12]:
len(HK)

279

In [13]:
#%load_ext sql

In [14]:
def createengine(name):
  engine = sqlalchemy.create_engine('sqlite:///'+name)
  return engine

In [15]:
HKengine = createengine('HK')

In [16]:
def TOSQL(frames, symbols,engine):
  for frame,symbol in zip(frames,symbols):
      frame.to_sql(symbol,engine,index=False)
  print('Successfully imported data')

#frames 同 symbols 係2個唔同list, combine 2個唔同list and add to sql server

In [17]:
TOSQL(HK,HSI_symbol,HKengine)

Successfully imported data

In [25]:
stockcheck =pd.read_sql('Select * from "1698.HK"',HKengine)
stockcheck.set_index('Date',inplace=True)

In [26]:
stockcheck

,Open,High,Low,Close,Adj Close,Volume,Symbol
Date,,,,,,,
2022-09-21 00:00:00.000000,18.000000,18.299999,18.000000,18.219999,18.219999,396800,1698.HK
2022-09-22 00:00:00.000000,17.000000,17.299999,17.000000,17.200001,17.200001,102900,1698.HK
2022-09-23 00:00:00.000000,17.000000,17.000000,16.700001,16.740000,16.740000,44900,1698.HK
2022-09-26 00:00:00.000000,16.360001,16.440001,16.219999,16.400000,16.400000,43400,1698.HK
2022-09-27 00:00:00.000000,16.340000,16.360001,16.260000,16.360001,16.360001,83100,1698.HK
...,...,...,...,...,...,...,...
2023-02-07 00:00:00.000000,32.700001,32.900002,32.299999,32.700001,32.700001,16600,1698.HK
2023-02-08 00:00:00.000000,33.099998,33.049999,32.000000,32.200001,32.200001,49900,1698.HK
2023-02-09 00:00:00.000000,32.750000,34.099998,32.700001,33.950001,33.950001,56600,1698.HK
2023-02-10 00:00:00.000000,33.450001,33.450001,32.650002,32.900002,32.900002,31000,1698.HK
2023-02-13 00:00:00.000000,31.950001,32.650002,31.549999,32.349998,32.349998,15200,1698.HK